# Generated by Django 5.2.3 on 2026-01-31 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_quiz_course_course_topic_progress_quiz_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_slug', models.CharField(max_length=255)),
                ('display_title', models.CharField(max_length=255)),
                ('current_module_id', models.IntegerField(default=1)),
                ('completed_modules', models.JSONField(blank=True, default=list)),
                ('quiz_scores', models.JSONField(blank=True, default=dict)),
                ('last_visited_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_visited_at'],
                'unique_together': {('user', 'topic_slug')},
            },
        ),
    ]
