# Generated by Django 5.2.3 on 2026-03-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('generating', 'Generating'), ('generated', 'Generated'), ('failed', 'Failed')], default='generated', max_length=20),
        ),
    ]
