"use client"
import { useState } from 'react';
import { motion } from 'framer-motion';

interface MiniLab {
  title: string;
  description: string;
  preloaded_code?: string;
}

interface MiniProject {
  title: string;
  description: string;
  tasks: string[];
}

interface PracticeProblem {
  name: string;
  url: string;
}

interface QuizQuestion {
  question: string;
  options: string[];
  correct_answer?: string;
  answer?: string;
  correct_option?: string;
  explanation?: string;
}

interface QuizResult {
  question?: string;
  question_id: number;
  user_answer: string;
  correct_answer: string;
  is_correct: boolean;
  explanation?: string;
}

interface Module {
  name: string;
  description?: string;
  theory?: string;
  content?: string;
  preloaded_code?: string;
  mini_labs?: MiniLab[];
  mini_project?: MiniProject;
  practice_problems?: PracticeProblem[];
  quizzes?: { questions: QuizQuestion[] } | QuizQuestion[];
  quiz?: { questions: QuizQuestion[] } | QuizQuestion[];
}

interface PDFExporterProps {
  courseData?: {
    course_title?: string;
    course_content?: string;
    topic?: string;
    modules?: Module[];
  };
  quizResults?: {
    module_name?: string;
    results?: QuizResult[];
    total_questions?: number;
    correct_answers?: number;
    score_percentage?: number;
  };
  type: 'course' | 'quiz';
}

export default function PDFExporter({ courseData, quizResults, type }: PDFExporterProps) {
  const [isGenerating, setIsGenerating] = useState(false);

  const exportToPDF = async () => {
    setIsGenerating(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      const contentWidth = pageWidth - 2 * margin;
      let yPosition = 30;

      // Define standard Header & Footer stamping routine
      const drawHeaderFooter = () => {
        const pageCount = doc.getNumberOfPages();
        if (pageCount === 1 && type === "course") return; // Skip header/footer on cover page

        // Draw Header
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8.5);
        doc.setTextColor(156, 163, 175); // Slate-400
        const headerTitle = courseData?.course_title || "MentAI Syllabus Report";
        doc.text(headerTitle, margin, 12);
        
        doc.setDrawColor(229, 231, 235); // Slate-200
        doc.setLineWidth(0.4);
        doc.line(margin, 15, pageWidth - margin, 15);

        // Draw Footer
        doc.text(`Page ${pageCount}`, pageWidth - margin - 12, 287);
        doc.text("Generated by MentAI Learning Platform", margin, 287);
      };

      // Define safe multiline text printing routine with automatic page break handling
      const addText = (
        text: string,
        options: {
          fontSize?: number;
          fontStyle?: 'normal' | 'bold' | 'italic';
          textColor?: [number, number, number];
          lineHeight?: number;
          indent?: number;
          spacingAfter?: number;
        } = {}
      ) => {
        const {
          fontSize = 10,
          fontStyle = 'normal',
          textColor = [31, 41, 55], // Slate-800
          lineHeight = 5.2,
          indent = 0,
          spacingAfter = 4
        } = options;

        doc.setFont("helvetica", fontStyle);
        doc.setFontSize(fontSize);
        doc.setTextColor(textColor[0], textColor[1], textColor[2]);

        const lines = doc.splitTextToSize(text, contentWidth - indent);
        
        lines.forEach((line: string) => {
          if (yPosition > 272) {
            doc.addPage();
            drawHeaderFooter();
            yPosition = 25;
            // Restore font configuration inside new page closure
            doc.setFont("helvetica", fontStyle);
            doc.setFontSize(fontSize);
            doc.setTextColor(textColor[0], textColor[1], textColor[2]);
          }
          doc.text(line, margin + indent, yPosition);
          yPosition += lineHeight;
        });

        yPosition += spacingAfter;
      };

      // Define specialized wrapped code block formatting
      const addCodeBlock = (code: string) => {
        doc.setFont("courier", "normal");
        doc.setFontSize(9);
        doc.setTextColor(31, 41, 55);

        const codeLines = doc.splitTextToSize(code, contentWidth - 10);
        const blockHeight = codeLines.length * 4.8 + 6;

        if (yPosition + blockHeight > 265) {
          doc.addPage();
          drawHeaderFooter();
          yPosition = 25;
        }

        // Background box for code snippet container
        doc.setFillColor(243, 244, 246); // Slate-100
        doc.rect(margin, yPosition - 4, contentWidth, blockHeight, "F");

        codeLines.forEach((line: string) => {
          doc.text(line, margin + 5, yPosition);
          yPosition += 4.8;
        });

        yPosition += 8;
        doc.setFont("helvetica", "normal");
      };

      // Define visual divider
      const addDivider = (spacingBefore = 4, spacingAfter = 6) => {
        yPosition += spacingBefore;
        if (yPosition > 270) {
          doc.addPage();
          drawHeaderFooter();
          yPosition = 25;
          return;
        }
        doc.setDrawColor(243, 244, 246); // Slate-100
        doc.setLineWidth(0.5);
        doc.line(margin, yPosition, pageWidth - margin, yPosition);
        yPosition += spacingAfter;
      };

      if (type === "course" && courseData) {
        // --- 1. COVER PAGE ---
        // Header Banner Background block
        doc.setFillColor(30, 41, 59); // Slate-800
        doc.rect(0, 0, pageWidth, 90, "F");

        // Small decorative accent bar
        doc.setFillColor(59, 130, 246); // Blue-500
        doc.rect(0, 90, pageWidth, 4, "F");

        // White Header Title Text
        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.setTextColor(191, 219, 254); // Light Blue accent
        doc.text("MENTAI COMPLETE COURSE SYLLABUS", pageWidth / 2, 38, { align: "center" });

        doc.setFontSize(26);
        doc.setTextColor(255, 255, 255);
        const titleLines = doc.splitTextToSize(courseData.course_title || "Course Syllabus", contentWidth);
        let titleY = 52;
        titleLines.forEach((line: string) => {
          doc.text(line, pageWidth / 2, titleY, { align: "center" });
          titleY += 10;
        });

        // Content Area below banner
        yPosition = 120;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);
        doc.setTextColor(107, 114, 128); // Gray-500
        doc.text(`Topic Category: ${courseData.topic || "Computer Science"}`, margin, yPosition);
        yPosition += 8;
        doc.text(`Generated on: ${new Date().toLocaleDateString()}`, margin, yPosition);
        yPosition += 20;

        // Executive summary text
        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.setTextColor(17, 24, 39);
        doc.text("Course Overview", margin, yPosition);
        yPosition += 8;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);
        doc.setTextColor(55, 65, 81);
        const descLines = doc.splitTextToSize(courseData.course_content || "No course summary available.", contentWidth);
        descLines.forEach((line: string) => {
          doc.text(line, margin, yPosition);
          yPosition += 6;
        });

        // Add page break to separate cover page from module breakdown
        doc.addPage();
        drawHeaderFooter();
        yPosition = 25;

        // --- 2. MODULE DETAILS ---
        courseData.modules?.forEach((module: Module, idx: number) => {
          // Keep a fresh page for each main module to preserve document cleanliness
          if (idx > 0) {
            doc.addPage();
            drawHeaderFooter();
            yPosition = 25;
          }

          // Module Header Banner accent
          doc.setFillColor(239, 246, 255); // Slate-50 background container
          doc.rect(margin, yPosition - 4, contentWidth, 12, "F");

          // Module Heading
          addText(module.name || `Module ${idx + 1}`, {
            fontSize: 15,
            fontStyle: 'bold',
            textColor: [17, 24, 39], // Slate-900
            lineHeight: 6,
            spacingAfter: 4
          });

          // Module description
          if (module.description && module.description !== "Master this concept.") {
            addText(module.description, {
              fontSize: 10.5,
              fontStyle: 'italic',
              textColor: [75, 85, 99], // Gray-600
              lineHeight: 5.2,
              spacingAfter: 6
            });
          }

          addDivider(2, 6);

          // Detailed Theory Section
          if (module.theory) {
            addText("Theory & Core Concepts", {
              fontSize: 12.5,
              fontStyle: 'bold',
              textColor: [29, 78, 216], // Primary Blue
              spacingAfter: 4
            });

            const cleanTheory = module.theory
              .replace(/###\s*(.*)/g, '$1')
              .replace(/##\s*(.*)/g, '$1')
              .replace(/#\s*(.*)/g, '$1')
              .replace(/\*\*(.*?)\*\*/g, '$1')
              .replace(/`([^`]+)`/g, '$1');

            addText(cleanTheory, {
              fontSize: 10,
              textColor: [55, 65, 81], // Slate-700
              lineHeight: 5.2,
              spacingAfter: 8
            });
          }

          // Interactive Programming Labs
          if (module.mini_labs && module.mini_labs.length > 0) {
            addText("Interactive Code Labs", {
              fontSize: 12.5,
              fontStyle: 'bold',
              textColor: [5, 150, 105], // Emerald Green
              spacingAfter: 4
            });

            module.mini_labs.forEach((lab: MiniLab, labIdx: number) => {
              addText(`${labIdx + 1}. ${lab.title || "Interactive Challenge"}`, {
                fontSize: 10.5,
                fontStyle: 'bold',
                textColor: [17, 24, 39],
                spacingAfter: 2,
                indent: 4
              });

              addText(lab.description, {
                fontSize: 10,
                textColor: [55, 65, 81],
                lineHeight: 5,
                spacingAfter: 4,
                indent: 4
              });

              if (lab.preloaded_code) {
                addCodeBlock(lab.preloaded_code);
              }
            });
          }

          // Mini Project Implementation
          if (module.mini_project) {
            addText(`Practical Project: ${module.mini_project.title}`, {
              fontSize: 12.5,
              fontStyle: 'bold',
              textColor: [124, 58, 237], // Purple
              spacingAfter: 4
            });

            addText(module.mini_project.description, {
              fontSize: 10,
              textColor: [55, 65, 81],
              lineHeight: 5,
              spacingAfter: 4
            });

            if (module.mini_project.tasks && module.mini_project.tasks.length > 0) {
              addText("Implementation Checklist:", {
                fontSize: 10.5,
                fontStyle: 'bold',
                textColor: [17, 24, 39],
                spacingAfter: 3,
                indent: 4
              });

              module.mini_project.tasks.forEach((task: string, taskIdx: number) => {
                addText(`[ ] ${task}`, {
                  fontSize: 9.5,
                  textColor: [75, 85, 99],
                  lineHeight: 4.8,
                  indent: 8,
                  spacingAfter: 2
                });
              });
              yPosition += 4;
            }
          }

          // Practice Problems Links
          if (module.practice_problems && module.practice_problems.length > 0) {
            addText("External Practice Problems", {
              fontSize: 12.5,
              fontStyle: 'bold',
              textColor: [217, 119, 6], // Amber-600
              spacingAfter: 4
            });

            module.practice_problems.forEach((prob: PracticeProblem) => {
              addText(`* ${prob.name} (${prob.url})`, {
                fontSize: 9.5,
                textColor: [29, 78, 216],
                spacingAfter: 2,
                indent: 4
              });
            });
            yPosition += 4;
          }

          // Self-Assessment Quizzes
          const quizData = module.quizzes || module.quiz;
          let quizQuestions: QuizQuestion[] = [];

          if (Array.isArray(quizData)) {
            quizQuestions = quizData;
          } else if (quizData && quizData.questions && Array.isArray(quizData.questions)) {
            quizQuestions = quizData.questions;
          }

          if (quizQuestions.length > 0) {
            addText("Self-Evaluation Practice Quiz", {
              fontSize: 12.5,
              fontStyle: 'bold',
              textColor: [30, 41, 59], // Slate-700
              spacingAfter: 4
            });

            quizQuestions.forEach((q: QuizQuestion, qIdx: number) => {
              addText(`Q${qIdx + 1}. ${q.question}`, {
                fontSize: 10.5,
                fontStyle: 'bold',
                textColor: [17, 24, 39],
                spacingAfter: 3,
                indent: 4
              });

              if (q.options && Array.isArray(q.options)) {
                q.options.forEach((opt: string, optIdx: number) => {
                  const prefix = `  [${String.fromCharCode(65 + optIdx)}] `;
                  addText(prefix + opt, {
                    fontSize: 9.5,
                    textColor: [75, 85, 99],
                    lineHeight: 4.8,
                    spacingAfter: 2,
                    indent: 8
                  });
                });
              }

              const correctAns = q.correct_answer || q.answer || q.correct_option || "";
              addText(`Correct Choice: ${correctAns}`, {
                fontSize: 9.5,
                fontStyle: 'bold',
                textColor: [5, 150, 105], // Green
                spacingAfter: q.explanation ? 2 : 4,
                indent: 8
              });

              if (q.explanation) {
                addText(`Explanation: ${q.explanation}`, {
                  fontSize: 9,
                  fontStyle: 'italic',
                  textColor: [107, 114, 128],
                  lineHeight: 4.5,
                  spacingAfter: 6,
                  indent: 8
                });
              }
            });
          }
        }); // Close module loop
      } else if (type === "quiz" && quizResults) {
        // --- 3. QUIZ PERFORMANCE REPORT ---
        // Blue Header Banner block
        doc.setFillColor(30, 41, 59); // Slate-800
        doc.rect(0, 0, pageWidth, 60, "F");

        // Small decorative accent bar
        doc.setFillColor(124, 58, 237); // Purple accent
        doc.rect(0, 60, pageWidth, 3, "F");

        doc.setFont("helvetica", "bold");
        doc.setFontSize(20);
        doc.setTextColor(255, 255, 255);
        doc.text("MENTAI PERFORMANCE REPORT", pageWidth / 2, 28, { align: "center" });

        doc.setFontSize(11);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(196, 181, 253);
        doc.text(`Module Assessment: ${quizResults.module_name || "Quiz Review"}`, pageWidth / 2, 44, { align: "center" });

        yPosition = 75;

        // Score Card Summary Box
        doc.setFillColor(243, 244, 246); // Light Gray Background
        doc.rect(margin, yPosition - 5, contentWidth, 36, "F");

        // Inner vertical visual indicator
        const scorePct = quizResults.score_percentage || 0;
        let scoreColor: [number, number, number] = [220, 38, 38]; // Red-600
        if (scorePct >= 80) scoreColor = [5, 150, 105]; // Emerald-600
        else if (scorePct >= 60) scoreColor = [217, 119, 6]; // Amber-600

        doc.setFillColor(scoreColor[0], scoreColor[1], scoreColor[2]);
        doc.rect(margin, yPosition - 5, 4, 36, "F");

        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.setTextColor(17, 24, 39);
        doc.text("Performance Overview", margin + 8, yPosition + 4);

        doc.setFont("helvetica", "normal");
        doc.setFontSize(10.5);
        doc.setTextColor(55, 65, 81);
        doc.text(`Total Questions Evaluated: ${quizResults.total_questions || 0}`, margin + 8, yPosition + 14);
        doc.text(`Correctly Answered Items: ${quizResults.correct_answers || 0}`, margin + 8, yPosition + 22);

        doc.setFont("helvetica", "bold");
        doc.setFontSize(16);
        doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
        doc.text(`Score: ${scorePct.toFixed(1)}%`, margin + 115, yPosition + 16);

        yPosition += 45;

        // Detailed Results List
        if (quizResults.results && quizResults.results.length > 0) {
          addText("Detailed Performance Breakdown", {
            fontSize: 13,
            fontStyle: 'bold',
            textColor: [17, 24, 39],
            spacingAfter: 6
          });

          quizResults.results.forEach((res: QuizResult, idx: number) => {
            const questionTitle = res.question || `Question ${idx + 1}`;
            addText(`Q${idx + 1}. ${questionTitle}`, {
              fontSize: 10.5,
              fontStyle: 'bold',
              textColor: [17, 24, 39],
              spacingAfter: 3
            });

            const isCorrect = res.is_correct;
            addText(`Your Answer: ${res.user_answer || "Not Answered"}`, {
              fontSize: 9.5,
              fontStyle: isCorrect ? 'normal' : 'bold',
              textColor: isCorrect ? [5, 150, 105] : [220, 38, 38], // Emerald Green / Red
              indent: 4,
              spacingAfter: 2
            });

            if (!isCorrect) {
              addText(`Correct Selection: ${res.correct_answer}`, {
                fontSize: 9.5,
                fontStyle: 'bold',
                textColor: [5, 150, 105], // Green
                indent: 4,
                spacingAfter: 2
              });
            }

            if (res.explanation) {
              addText(`Explanation: ${res.explanation}`, {
                fontSize: 9,
                fontStyle: 'italic',
                textColor: [107, 114, 128], // Slate-500
                lineHeight: 4.5,
                indent: 4,
                spacingAfter: 6
              });
            } else {
              yPosition += 3;
            }
          });
        }
      }

      let fileName = "MentAI_Export.pdf";
      if (type === "course") {
        const topicName = courseData?.topic || courseData?.course_title?.replace("Complete ", "").replace(" Mastery Course", "") || "Course";
        fileName = `MentAI - ${topicName} Syllabus.pdf`;
      } else {
        fileName = `${quizResults?.module_name || 'Quiz'}_Report.pdf`;
      }

      doc.save(fileName);
    } catch (error) {
      console.error("Error generating PDF:", error);
      alert("Error generating PDF. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <motion.button
      whileHover={{ scale: 1.03 }}
      whileTap={{ scale: 0.97 }}
      onClick={exportToPDF}
      disabled={isGenerating}
      className="px-5 py-2.5 bg-[#06B6D4] text-[#111827] rounded-lg hover:bg-[#06b6d4]/90 disabled:bg-gray-400 disabled:cursor-not-allowed transition-all shadow-md flex items-center space-x-2 font-semibold text-sm"
    >
      {isGenerating ? (
        <>
          <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-[#111827]"></div>
          <span>Generating PDF...</span>
        </>
      ) : (
        <>
          <span>Export {type === 'course' ? 'Course' : 'Quiz'} as PDF</span>
        </>
      )}
    </motion.button>
  );
}